#pragma once

#define DBG_DISABLE_ALL_MOTORS     ( 0 )
#define DBG_DISABLE_ARM_MOTORS     ( 0 || DBG_DISABLE_ALL_MOTORS )
#define DBG_DISABLE_WRIST_MOTORS   ( 0 || DBG_DISABLE_ALL_MOTORS )
#define DBG_DISABLE_CLIMB_MOTORS   ( 0 || DBG_DISABLE_ALL_MOTORS )
#define DBG_DISABLE_SHOOT_MOTORS   ( 0 || DBG_DISABLE_ALL_MOTORS )
#define DBG_DISABLE_INTAKE_MOTORS  ( 0 || DBG_DISABLE_ALL_MOTORS )

#define DBG_MANUAL_CONTROL_ALL_MOTORS     ( 0 )
#define DBG_MANUAL_CONTROL_ARM_MOTORS     ( 0 || DBG_MANUAL_CONTROL_ALL_MOTORS )
#define DBG_MANUAL_CONTROL_WRIST_MOTORS   ( 0 || DBG_MANUAL_CONTROL_ALL_MOTORS )
#define DBG_MANUAL_CONTROL_CLIMB_MOTORS   ( 0 || DBG_MANUAL_CONTROL_ALL_MOTORS )
#define DBG_MANUAL_CONTROL_SHOOT_MOTORS   ( 0 || DBG_MANUAL_CONTROL_ALL_MOTORS )
#define DBG_MANUAL_CONTROL_INTAKE_MOTORS  ( 0 || DBG_MANUAL_CONTROL_ALL_MOTORS )
